name: jobs parallel execution
on:
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: first step on build image
        run: |
          echo "fist steps"
  Publist-build-image:
    runs-on: ubuntu-latest
    steps:
      - name: first step on build image
        run: |
          echo "fist steps"