name: jobs parallel execution
on:
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: first step on build image
        run: |
          echo "fist steps"
  build-image12:
    runs-on: ubuntu-latest
    steps:
    - name: first step on build image
      run: |
        echo "fist steps"
  Publist-build-image:
    runs-on: ubuntu-latest
    needs: 
      - azure_build
    steps:
      - name: first step on build image
        run: |
          echo "fist steps"
  azure_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
      - name: az bicep deploy
        working-directory: '${{github.workspace}}/src/bicep'
        run:
          az deployment group create -g azbicepresourcegroup -f storage_account_test.bicep
  azure_build4:
    runs-on: ubuntu-latest
    needs: 
        - azure_build
        - build-image
        - Publist-build-image
        - build-image12
    steps:
      - name: first step on build image
        run: |
          echo "fist steps"


    
  