name: Get Git Event Number
on:
  push:
    branches:
      - main
env:
  PR_NUMBER: ${{ github.event.number }}
jobs:
  get_git_event_number:
    runs-on: ubuntu-latest
    steps:
    - name: Print Event Number
      run: |
          echo "Event Number: ${{ github.event.number }}"

