name: Get Git Event Number
on:
  push:
    branches:
      - main
env:
  PR_NUMBER: ${{ github.event.number }}
jobs:
  get_git_event_number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      

